### ISSUE TITLE
Nametag doesn't disappear

### ISSUE THREAD

**Issue by arin2115** [ploppyperson/StackMob-5#302]
References #301 

The problem still remains if multiple entities in a stack are killed in one hit.

For example if I have 3 pigs in a stack and I kill them all with a single hit, the nametag will remain at the death place till server restart.

**Comment by ploppyperson** [comment]
Is this from the latest commit?

________________________________
From: just arin ***@***.***>
Sent: Wednesday, January 29, 2025 6:56:54 PM
To: ploppyperson/StackMob-5 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ploppyperson/StackMob-5] Nametag doesn't disappear (Issue #302)


References #301<https://github.com/ploppyperson/StackMob-5/issues/301>

The problem still remains if multiple entities in a stack are killed in one hit.

For example if I have 3 pigs in a stack and I kill them all with a single hit, the nametag will remain at the death place till server restart.

**Comment by arin2115** [comment]
Yep, latest commit

**Comment by ploppyperson** [comment]
Try now

**Comment by arin2115** [comment]
Yep, it works now, thanks!

Also maybe I'm doing something wrong, but I think that Jobs dependency in pom.xml should have version "v4.17.2" instead of just "4.17.2" as it doesnt compile otherwise (it is "v4.17.2" on jitpack so yeah)

**Comment by andrewkm** [comment]
> Yep, it works now, thanks!
> 
> Also maybe I'm doing something wrong, but I think that Jobs dependency in pom.xml should have version "v4.17.2" instead of just "4.17.2" as it doesnt compile otherwise (it is "v4.17.2" on jitpack so yeah)

Compiling is working fine on our end.
https://ci.ecocitycraft.com/job/StackMob-5/789/console

**Comment by arin2115** [comment]
Actually on your end it says
`[WARNING] The POM for com.github.Zrips:Jobs:jar:4.17.2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details`
It's just a warning, however when I'm compiling with "mvn clean install" it throws an error as this dependency cannot be downloaded.
And as said, 4.17.2 doesn't exist ([jitpack](https://jitpack.io/#Zrips/Jobs/v4.17.2))

**Comment by arin2115** [comment]
Seems like there is another issue, after breeding for example cows, and after they grow up, nametags are left behind.

![Image](https://github.com/user-attachments/assets/5f83849b-815d-45ad-8ca8-2fca62eae7e3)

**Comment by andrewkm** [comment]
Name tags be plaguing our servers! xD

**Comment by ploppyperson** [comment]
> Seems like there is another issue, after breeding for example cows, and after they grow up, nametags are left behind.
> 
> ![Image](https://github.com/user-attachments/assets/5f83849b-815d-45ad-8ca8-2fca62eae7e3)

This is only for mobs that have been bred?

**Comment by andrewkm** [comment]
@arin2115 I just tried with mvn clean install, and it worked, but the warning persists, you're right:
https://ci.ecocitycraft.com/job/StackMob-5/790/console

@ploppyperson may as well up this to https://jitpack.io/#Zrips/Jobs/v5.2.2.3

**Comment by andrewkm** [comment]
@ploppyperson I'm going to have someone come by and report a few other name tag issues shortly once they are finished testing. Seems there's a few other problems as well so may as well keep them in this thread.

**Comment by arin2115** [comment]
> This is only for mobs that have been bred?

Happened to me by breeding them and waiting till they grow up, so yeah.

Didn't have any other problems so far, just this

**Comment by ploppyperson** [comment]
try now

**Comment by arin2115** [comment]
Seems like it's working properly now, will see later with more players

**Comment by arin2115** [comment]
Issue still persists, and idk if its not even worse now.

![Image](https://github.com/user-attachments/assets/514737ae-7ad9-4f9b-b28f-d4726932d610)

**Comment by ploppyperson** [comment]
@arin2115 @Mrvivivici Do you know what the cause is?

**Comment by arin2115** [comment]
? As I stated before, it happens cuz of breeding a stack of animals, once breeded stack grows up, it lefts the text display behind instead of removing it. At least I think that is why. Also it seems like after a server restart, or something else the displays are removed

**Comment by crumpkatrina** [comment]
We are also still experiencing this but not with breeding mobs.
We have a butcher that automatically clears all mobs on one of our worlds and the tags are left behind after the mobs are cleared via butcher.
https://i.imgur.com/4Xa2L5v.png

**Comment by andrewkm** [comment]
@ploppyperson I can confirm, even WorldEdit's **/butcher** command is causing the name tags to stick around but the mobs disappear just fine.
Please help lol. <3

**Comment by ploppyperson** [comment]
hopefully this is the last time...

**Comment by andrewkm** [comment]
> hopefully this is the last time...

Unable to test @ploppyperson 
https://pastebin.com/efsi5bRZ

[ERROR] /var/lib/jenkins/workspace/StackMob-5/src/main/java/uk/antiperson/stackmob/entity/tags/DisplayTagListeners.java:[41,87] incompatible types: org.bukkit.entity.Entity cannot be converted to org.bukkit.entity.LivingEntity

**Comment by andrewkm** [comment]
@ploppyperson looks like that didn't fix compile.
https://ci.ecocitycraft.com/job/StackMob-5/798/console

**Comment by ploppyperson** [comment]
I take it has been fixed? I can't test right now.

**Comment by andrewkm** [comment]
> I take it has been fixed? I can't test right now.

I've had a few IRL emergencies and haven't been able to get to it, I will be testing tonight though. :)

**Comment by andrewkm** [comment]
@ploppyperson All issues on my end have been fixed.

**Comment by johncsuti** [comment]
![Image](https://github.com/user-attachments/assets/47deda28-24ce-47ee-81af-22d3e2d0ee86)

Running the fallowing build using Purpur 1.21.3-2358 nametags do not disappear after a server restart.

https://ci.ecocitycraft.com/job/StackMob-5/808

**Comment by andrewkm** [comment]
> ![Image](https://github.com/user-attachments/assets/47deda28-24ce-47ee-81af-22d3e2d0ee86)
> 
> Running the fallowing build using Purpur 1.21.3-2358 nametags do not disappear after a server restart.
> 
> https://ci.ecocitycraft.com/job/StackMob-5/808

Interesting, our issues have been fully fixed however we are on Paper 1.21.4.

**Comment by ploppyperson** [comment]
> ![Image](https://github.com/user-attachments/assets/47deda28-24ce-47ee-81af-22d3e2d0ee86)
> 
> Running the fallowing build using Purpur 1.21.3-2358 nametags do not disappear after a server restart.
> 
> https://ci.ecocitycraft.com/job/StackMob-5/808

Are you sure the entities were killed after you updated to the latest build?

**Comment by johncsuti** [comment]
> > ![Image](https://github.com/user-attachments/assets/47deda28-24ce-47ee-81af-22d3e2d0ee86)
> > Running the fallowing build using Purpur 1.21.3-2358 nametags do not disappear after a server restart.
> > https://ci.ecocitycraft.com/job/StackMob-5/808
> 
> Are you sure the entities were killed after you updated to the latest build?

Not sure when the entities were killed is there any way to remove the nametags regardless? Id rather not reset the world.

**Comment by ploppyperson** [comment]
> > > ![Image](https://github.com/user-attachments/assets/47deda28-24ce-47ee-81af-22d3e2d0ee86)
> > > Running the fallowing build using Purpur 1.21.3-2358 nametags do not disappear after a server restart.
> > > https://ci.ecocitycraft.com/job/StackMob-5/808
> > 
> > 
> > Are you sure the entities were killed after you updated to the latest build?
> 
> Not sure when the entities were killed is there any way to remove the nametags regardless? Id rather not reset the world.

'/minecraft:kill @e[type=minecraft:text_display,distance=..20]'

**Comment by andrewkm** [comment]
> > > > ![Image](https://github.com/user-attachments/assets/47deda28-24ce-47ee-81af-22d3e2d0ee86)
> > > > Running the fallowing build using Purpur 1.21.3-2358 nametags do not disappear after a server restart.
> > > > https://ci.ecocitycraft.com/job/StackMob-5/808
> > > 
> > > 
> > > Are you sure the entities were killed after you updated to the latest build?
> > 
> > Not sure when the entities were killed is there any way to remove the nametags regardless? Id rather not reset the world.
> 
> '/minecraft:kill @e[type=minecraft:text_display,distance=..20]'
> 

This is a very handy command, thank you. :)

**Comment by johncsuti** [comment]
Just wanted to update this did end up fixing the issue

**Comment by ploppyperson** [comment]
Is this with the build from the CI?
________________________________
